#!/bin/bash
 #banner
cat banner.txt;

#Variaveis
SERVER_URL="https://minecraft.azureedge.net/bin-linux/bedrock-server-1.14.60.5.zip"
SERVER_UPDATE="$(wget -qO- https://raw.githubusercontent.com/Sirherobrine23/Minecraft-Bedrock-auto-install/master/Update.txt)"
PATH_TO_INSTALL="/mnt/d/teste/Minecraft"
PATH_TO_BACKUP="/mnt/d/teste/Minecraft-Backup"
IP_V4=$(hostname -i)
IP_V6=$(hostname -I)
IP_PUBLICO=$(wget -qO- ifconfig.me)
file=mcpe
FILE2=mcpe-start.txt
MAPA=$(cat $TMP/level.txt)
BACKUP="$(TZ=UTC+3 date +"%d-%m-%Y")"
TMP=/mnt/d/teste/tmp
rm -rf $TMP/level.txt
cat "$PATH_TO_INSTALL/mcpe/server.properties" | grep "level-name=" > "$TMP/level.txt" ; sed -i "s|level-name=||g" "$TMP/level.txt";

echo " "

case $1 in
   "-h") cat help.txt ; echo " "
         ;;
   "--help") cat help.txt ; echo " "
         ;;
   "--install") 
            # Prerequisite
            echo "  ";
            echo "Instalando os Pré-reuisitos para o debian, ubuntu";
            echo -ne "#                         (01%)\r";
            sudo apt install -y wget unzip ;
            echo -ne "##                        (02%)\r";
            sudo mkdir $PATH_TO_INSTALL ;
            #Download do arquivos servidor
            sudo wget $SERVER_URL -O $PATH_TO_INSTALL/mcpe.zip ;
            echo -ne "########                  (40%)\r";
            sudo unzip $PATH_TO_INSTALL/mcpe.zip -d $PATH_TO_INSTALL/mcpe ;
            sudo rm -r $PATH_TO_INSTALL/mcpe.zip;
            echo -ne "#############             (50%)\r";
            #config
            rm -rf $PATH_TO_INSTALL/mcpe/server.properties
            rm -rf $PATH_TO_INSTALL/mcpe/whitelist.json
            cp -r ./server.properties $PATH_TO_INSTALL/mcpe/
            cp -r ./whitelist.json $PATH_TO_INSTALL/mcpe/
            echo -ne "#######################   (100%)\r";
            echo -ne "####### completo ######   (100%)\r";
      ;;
      "--update")
            bash teste.sh
      ;;
      "--screen") 
            #install
            echo "Instalando o Screen ";
            sudo apt install -y screen ;
            ./menu --ubuntu;
      ;;
      "--start-file")
            #Config File
            rm -rf /tmp/level.txt
            cat $FILE2 > "$file"
            cat $PATH_TO_INSTALL/mcpe/server.properties | grep "level-name=" > /tmp/level.txt ; sed -i "s|level-name=||g" "/tmp/level.txt"
            sed -i "s|DIRE|$PATH_TO_INSTALL|g" "$file";
            sed -i "s|MAPASS|$(cat /tmp/level.txt)|g" "$file"
            sed -i "s|PATH_TO_INSTALL|$PATH_TO_INSTALL|g" "$file"
            sudo cp "$file" /sbin/mcpe ; sudo chmod a+x /sbin/mcpe ; 
      ;;
      "--ip")
            cp ips.txt /tmp/ip.txt;
            sed -i "s|IPV4|$IP_V4|g" "/tmp/ip.txt";
            sed -i "s|IPV6|$IP_V6|g" "/tmp/ip.txt";
            sed -i "s|IPPUBLICO|$IP_PUBLICO|g" "/tmp/ip.txt";
            cat /tmp/ip.txt;
            rm -r /tmp/ip.txt
            echo " ";
      ;;
      "--unistall") sudo rm -rf ../installer
      ;;
   *) echo "Opção inválida! utilize a opção -h"
      exit 1
      ;;
esac