#!/bin/bash
clear
#Variaveis
SERVER_URL="https://minecraft.azureedge.net/bin-linux/bedrock-server-1.14.60.5.zip"
SERVER_UPDATE="$(wget -qO- https://raw.githubusercontent.com/Sirherobrine23/Minecraft-Bedrock-auto-install/master/Update.txt)"
PATH_TO_INSTALL="/home/Minecraft"
PATH_TO_BACKUP="/home/Minecraft-Backup"
IP_V4=$(hostname -i)
IP_V6=$(hostname -I)
IP_PUBLICO=$(wget -qO- ifconfig.me)
file=mcpe
FILE2=mcpe-start.txt
BACKUP="$(TZ=UTC+3 date +"%d-%m-%Y")"
TMP=/home/Minecraft/tmp &> ./log.txt;
sudo mkdir $TMP &> ./log.txt;
rm -rf $TMP/level.txt &> ./log.txt;
cat "$PATH_TO_INSTALL/mcpe/server.properties" | grep "level-name=" > "$TMP/level.txt" ; sed -i "s|level-name=||g" "$TMP/level.txt" &> ./log.txt;
MAPA=$(cat $TMP/level.txt)
echo " "

case $1 in
   "--install") 
             #banner
            cat banner.txt;
            # Prerequisite
            echo "  ";
            echo "Instalando os Pré-reuisitos para o debian, ubuntu";
            echo -ne "#                         (01%)\r";
            sudo apt install -y wget unzip 2>> log.txt &> ./log.txt;
            echo -ne "##                        (02%)\r";
            sudo mkdir $PATH_TO_INSTALL &> ./log.txt;
            #Download do arquivos servidor
            sudo wget $SERVER_URL -O $PATH_TO_INSTALL/mcpe.zip &> ./log.txt;
            echo -ne "########                  (40%)\r";
            sudo unzip -o $PATH_TO_INSTALL/mcpe.zip -d $PATH_TO_INSTALL/mcpe &> ./log.txt;
            sudo rm -rf $PATH_TO_INSTALL/mcpe.zip;
            echo -ne "#############             (50%)\r";
            #config
            rm -rf $PATH_TO_INSTALL/mcpe/server.properties &> ./log.txt;
            rm -rf $PATH_TO_INSTALL/mcpe/whitelist.json &> ./log.txt;
            cp -r ./server.properties $PATH_TO_INSTALL/mcpe/ &> ./log.txt;
            cp -r ./whitelist.json $PATH_TO_INSTALL/mcpe/ &> ./log.txt;
            echo -ne "#######################   (100%)\r";
            echo -ne "####### completo ######   (100%)\r";
            sudo cat "./log.txt"
      ;;
      "--update")
             #banner
            cat banner.txt;
            #Copiando
            echo -ne "                          (0%)\r";
            sudo mkdir $PATH_TO_BACKUP &> ./log.txt;
            sudo mkdir $PATH_TO_BACKUP/$BACKUP &> ./log.txt;            
            echo -ne "#                         (1%)\r";
            sudo cp -r $PATH_TO_INSTALL/mcpe/worlds/* $PATH_TO_BACKUP/$BACKUP &> ./log.txt;
            sudo cp $PATH_TO_INSTALL/mcpe/server.properties $PATH_TO_BACKUP/$BACKUP &> ./log.txt;
            sudo cp $PATH_TO_INSTALL/mcpe/whitelist.json $PATH_TO_BACKUP/$BACKUP &> ./log.txt;
            #Movendo versão antiga para $TMP
            echo -ne "##                       (10%)\r";
            
            sudo mv $PATH_TO_INSTALL $TMP &> ./log.txt;
            #Baixando
            sudo rm -rf $PATH_TO_INSTALL/mcpe.zip &> ./log.txt;
            sudo wget $SERVER_UPDATE -O $PATH_TO_INSTALL/mcpe.zip &> ./log.txt;
            sudo unzip -o $PATH_TO_INSTALL/mcpe.zip -d $PATH_TO_INSTALL/mcpe &> ./log.txt;
            sudo rm -r $PATH_TO_INSTALL/mcpe.zip &> ./log.txt;
            echo -ne "###########              (50%)\r";
            #Criando Diretorios
            sudo mkdir $PATH_TO_INSTALL &> ./log.txt;
            sudo mkdir $PATH_TO_INSTALL/mcpe &> ./log.txt;
            
            #Copiando mapa para nova versão
             sudo rm -rf $PATH_TO_INSTALL/worlds &> ./log.txt;
             sudo rm -rf $PATH_TO_INSTALL/server.properties &> ./log.txt;
             sudo rm -rf $PATH_TO_INSTALL/whitelist.json &> ./log.txt;
            sudo cp -r $PATH_TO_BACKUP/$BACKUP/$MAPA $PATH_TO_INSTALL/mcpe/worlds/ &> ./log.txt;
            sudo cp $PATH_TO_BACKUP/$BACKUP/server.properties $PATH_TO_INSTALL/mcpe/ &> ./log.txt;
            sudo cp $PATH_TO_BACKUP/$BACKUP/whitelist.json $PATH_TO_INSTALL/mcpe/ &> ./log.txt;

            sudo rm -rf $PATH_TO_INSTALL/mcpe/worlds/server.properties &> ./log.txt;
            sudo rm -rf $PATH_TO_INSTALL/mcpe/worlds/whitelist.json &> ./log.txt;
            sudo rm -r $PATH_TO_BACKUP
            echo -ne "#######################   (100%)\r";
            echo -ne "###### Completo #######   (100%)\r";
            sudo cat "./log.txt"
      ;;
      "--screen") 
            #install
            echo "Instalando o Screen ";
            sudo apt install -y screen ;
            sudo bash menu --ubuntu;
            sudo mv mcpe /sbin/ ; sudo chmod a+x /sbin/mcpe;
      ;;
      "--start-file")
            #Config File
            rm -rf /tmp/level.txt
            cat $FILE2 > "$file"
            cat $PATH_TO_INSTALL/mcpe/server.properties | grep "level-name=" > /tmp/level.txt ; sed -i "s|level-name=||g" "/tmp/level.txt"
            sed -i "s|DIRE|$PATH_TO_INSTALL|g" "$file";
            sed -i "s|MAPASS|$(cat /tmp/level.txt)|g" "$file"
            sed -i "s|PATH_TO_INSTALL|$PATH_TO_INSTALL|g" "$file"
            sudo cp "$file" /sbin/mcpe ; sudo chmod a+x /sbin/mcpe ; 
      ;;
      "--start-on-system")
            sudo cp start-on-system /etc/init.d/mcpe;
            echo "copiando o arquivo";
            sudo chmod a+x /etc/init.d/mcpe;
            echo 'service mcpe start|stop|restart'
            echo 'teste caso não inicie o servidor é por causa, que não instalaram o script "start-file"'
      ;;
      "--ip")
            cp ips.txt /tmp/ip.txt;
            sed -i "s|IPV4|$IP_V4|g" "/tmp/ip.txt";
            sed -i "s|IPV6|$IP_V6|g" "/tmp/ip.txt";
            sed -i "s|IPPUBLICO|$IP_PUBLICO|g" "/tmp/ip.txt";
            cat /tmp/ip.txt;
            rm -r /tmp/ip.txt
            echo " ";
      ;;
      "--unistall") sudo rm -rf ../installer
      ;;
   *) cat banner.txt ; cat help.txt ; echo " ";
      exit 1
      ;;
esac