# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler/blob/master/README.md

name: Tag-linux
on:
  push:
    branches:
      - Beta
    paths:
      - .gitgnore
      - banner.txt
      - help.txt
      - install.sh
      - menu.sh
      - mcpe-start.sh
      - server.properties
      - whitelist.json
      - start-on-system.sh
      - Update.txt

jobs:
  Tag:

    runs-on: ubuntu-latest

    steps:
    - name: Gerando Tag
      id: tag
      run: |
        echo ::set-env name=RELEASE_TAG::"$(TZ=UTC+3 date +"%d/%m/%Y-%H-%M-%S")-tag-Linux"
        echo "Tag $(TZ=UTC+3 date +"%d/%m/%Y-%H-%M-%S")" >> release.txt
        echo "::set-output name=status::success"
    
    - name: tag
      uses: softprops/action-gh-release@v1
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.tag }}
      with:
        tag_name: ${{ env.RELEASE_TAG }}
        body_path: release.txt