name: Tag-Windows
on:
  push:
    branches:
      - Windows
    paths:
      - .gitgnore
      - install.bat
      - update.bat
      - zip/

jobs:
  Tag:

    runs-on: ubuntu-latest

    steps:
    - name: Gerando Tag
      id: tag
      run: |
        echo ::set-env name=RELEASE_TAG::"$(TZ=UTC+3 date +"%d/%m/%Y-%H-%M-%S")-tag-Windows"
        echo "Tag $(TZ=UTC+3 date +"%d/%m/%Y-%H-%M-%S")" >> release.txt
        echo "::set-output name=status::success"
    
    - name: Upload so Firmware para o Release
      uses: softprops/action-gh-release@v1
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.tag }}
      with:
        tag_name: ${{ env.RELEASE_TAG }}
        body_path: release.txt